simulation:
ifdef deadline
	python3 advance.py $(deadline)
else
	python3 advance.py
endif

processing:
ifdef deadline
	python3 process.py $(deadline)
else
	python3 process.py
endif

restart:
	python3 restart.py
